---
# tasks file for elixir
- name: "add erlange solutions repo"
  apt: deb="https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb"
  become: yes

- name: "install erlang/otp and all its dependencies"
  apt: name="esl-erlang" update_cache=yes state=present
  become: yes

- name: "install elixir"
  apt: name="elixir" update_cache=yes state=present
  become: yes
