---
# tasks file for common
- name: "install all common packages"
  apt: name={{ item }} state=latest
  with_items:
    - git
    - vim-nox
    - python-dev
    - python-pip
    - python-virtualenv
    - python-setuptools
    - flashplugin-installer

# install atom ide
- name: "install atom ide"
  apt: deb="https://github.com/atom/atom/releases/download/v1.8.0/atom-amd64.deb" state=present

